### ISSUE TITLE
filename letter case problem

### ISSUE THREAD

**Issue by craigsapp** [MeasuringPolyphony/measuring_polyphony_jekyll#4]
The filenames:

```
assets/mensural/post_Misse_MENSURAL.mei
assets/mensural/post_misse_MENSURAL.mei
```

Cause problems on MacOS, since it is semi-case insensitive.  So both files should not be in the same directory.  Probably the files represent the same piece, and they happened to be given slightly different names.  They should be compared and the older one or one with the incorrect letter cases should be removed.

This should be easy to do from the [github interface](https://github.com/MeasuringPolyphony/measuring_polyphony_jekyll/tree/master/assets/mensural), and probably should not be done by downloading onto a MacOS computer file system.

**Comment by craigsapp** [comment]
The only difference that I see is that one of them (presumably the newer one) has a tempo added:

```diff
--- a/assets/mensural/post_Misse_MENSURAL.mei
+++ b/assets/mensural/post_Misse_MENSURAL.mei
@@ -130,7 +130,7 @@
                <body xml:id="m-26">
                        <mdiv xml:id="m-27">
                                <score xml:id="m-28">
-                                       <scoreDef xml:id="m-29">
+                                       <scoreDef xml:id="m-29" midi.bpm="600">
```

**Comment by karend27** [comment]
Thanks for catching that - I got rid of the dupe.

**Comment by craigsapp** [comment]
You are supposed to click "Close with comment" when an issue is fixed (as I am doing now).
