### ISSUE TITLE
Github build of MP site failing

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/measuring_polyphony_jekyll#9]
Hi @craigsapp  - the build for the MP site is failing. This occurred since I updated links in the _layout pages from https://www.verovio.org/javascript/**develop**/verovio-toolkit.js" to "https://www.verovio.org/javascript/**latest**/verovio-toolkit.js
because of @lpugin new release of Verovio.
I committed the changes but the build failed. This is what @JRegimbal thinks might be going on: The error is about an apparent submodule (wildmidi), but looking at the last successful update to the website it seems the GitHub action has changed since then. Since this submodule doesn't seem to have changed since then, I think this is due to the behavior of the build action changing. Once this is working, it should build successfully and the URLs should update to the new version from Laurent. There doesn't seem to be a .gitmodules file, so the submodule either needs to be repaired (if you still use it) or fully deleted (if you don't).

@craigsapp do you think this is something that is an easy fix (that you could do :)? If it's more complicated - let's email.
(also copying in @martha-thomae as an FYI)

**Comment by craigsapp** [comment]
Hi @karend27,  I can run the latest version of MP from Github locally on my laptop and am able to see verovio-generated music and listen to the playback:

<img width="1000" alt="Screen Shot 2022-10-18 at 10 53 36 AM" src="https://user-images.githubusercontent.com/3487289/196507785-4fb37df7-4724-4d34-813c-dad069d76b4e.png">

When trying to get the website to run, there were lots of complaints which I was able to fix by switching from ruby v2.3.1 to ruby v2.7.0, but I don't think that would be a problem for Github Pages.   Does Github give a reason for the build fail?

I do not think that the website contains submodules, and wildwebmidi looks like it is still there (and I can hear the MIDI playback with the local build of the website on my laptop).

**Comment by karend27** [comment]
Hi @craigsapp - I'm also able to get the latest version to run locally on my laptop, and see the score and hear the audio. 

The GitHub build error is here: https://github.com/MeasuringPolyphony/measuring_polyphony_jekyll/actions/runs/2804132980

and more details here:
https://github.com/MeasuringPolyphony/measuring_polyphony_jekyll/actions/runs/2804125254/jobs/4423085558#step:10:10

<img width="1067" alt="Screen Shot 2022-10-18 at 5 49 19 PM" src="https://user-images.githubusercontent.com/11195203/196553788-4d6651bf-ec85-4ea9-aaa6-e0b82b770017.png">

**Comment by karend27** [comment]
@craigsapp the directory that is called wildwebmidi is empty I think (on my local version and also on Github). But there are two javascript files in the js directory that seem to have the midi functions:
https://github.com/MeasuringPolyphony/measuring_polyphony_jekyll/tree/master/js

I also found some possible related questions to missing .gitmodules, such as this:
https://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule

But I don't know how to do these sorts of changes to the repository through the command line (I only know how to work with Github desktop).

**Comment by karend27** [comment]
@JRegimbal was able to fix the issue with the wildmidi submodule. See her note appended to her pull request here: https://github.com/MeasuringPolyphony/measuring_polyphony_jekyll/pull/10
The pull request has been merged and the MP site is now loading and all Verovio aspects functioning (score display, midi playing, downloading PDFs).
